//file:noinspection GroovyAssignabilityCheck
plugins {
    id 'blib-multiloader-fabric'
}

dependencies {
    modApi "com.terraformersmc:modmenu:${project.modmenu_version}"
    modApi "dev.architectury:architectury-fabric:${project.architectury_version}"
    modApi "me.shedaniel.cloth:cloth-config-fabric:${project.cloth_version}"

    // Compatibility
    blibModCompileOnly "com.avp.human:avp_human-fabric-1.21.1:${project.avp_human_version}"
    blibModCompileOnly "com.avp.predator:avp_predator-fabric-1.21.1:${project.avp_predator_version}"
    blibMod "com.blib.engine:blib_engine-fabric-1.21.1:${project.blib_engine_version}"

    blibMod "maven.modrinth:gigeresque:${project.gigeresque_modrinth_version}"
    // Required for gigeresque.
    blibModRuntimeOnly "mod.azure.azurelib:azurelib-fabric-${project.minecraft_version}:${project.azurelib_version}"
}
