plugins {
    id 'blib-multiloader-root'
}

allprojects {
    repositories {
        mavenLocal()
    }
}

blib {
    version = project.blib_version
    recipeViewer = 'rei'

    mod {
        author = 'Stargazer Studios'
        description = 'A module for the AVP universe that adds alien content.'
        credits = 'Stargazer Studios'
        group = 'com.avp.alien'
        icon = 'assets/avp_alien/icon.png'
        id = 'avp_alien'
        license = 'All Rights Reserved'
        name = 'AVP (Alien)'
        version = '0.2.0-alpha.1'

        publish {
            dryRun = true

            discordWebhook {
                username = "MU/TH/UR"
                avatarUrl = "https://i.imgur.com/5Y0EZ9x.jpeg"
                thumbnailUrl = "https://cdn.modrinth.com/data/Uqo0H9FX/8ffabe2f364c34e6b0f13019664c5fe4989c2f95_96.webp"
            }

            curseforge {
                projectId = '1406354'
                projectSlug = 'avp-alien'
            }

            modrinth {
                projectId = '6PQ9G0rJ'
            }
        }
    }

    maven {
        repository 'https://maven.bvanseghi.dev/avp_human'
        repository 'https://maven.bvanseghi.dev/avp_predator'
        repository 'https://maven.bvanseghi.dev/blib_engine'

        publish {
            url = 'https://maven.bvanseghi.dev/avp_alien/'

            credentials {
                usernameEnv = 'AVP_MAVEN_USERNAME'
                passwordEnv = 'AVP_MAVEN_PASSWORD'
            }
        }
    }
}
