//file:noinspection GroovyAssignabilityCheck
plugins {
    id 'blib-multiloader-neoforge'
}

dependencies {
    blibMod "dev.architectury:architectury-neoforge:${project.architectury_version}"
    blibMod "me.shedaniel.cloth:cloth-config-neoforge:${project.cloth_version}"

    // Compatibility
    blibMod "com.avp.human:avp_human-neoforge-1.21.1:${project.avp_human_version}"
    blibMod "com.avp.predator:avp_predator-neoforge-1.21.1:${project.avp_predator_version}"

    blibMod "maven.modrinth:gigeresque:${project.gigeresque_version}"
    // Required for gigeresque.
    blibRuntimeOnly "mod.azure.azurelib:azurelib-neo-${project.minecraft_version}:${project.azurelib_version}"
}
